
set(Module_OTBImageManipulation ON CACHE BOOL "")
set(Module_OTBImageStatistics ON CACHE BOOL "")
set(Module_OTBMathParser ON CACHE BOOL "")
set(Module_OTBProjection ON CACHE BOOL "")
set(Module_OTBTransform ON CACHE BOOL "")
set(Module_OTBAppImageUtils ON CACHE BOOL "")
set(Module_OTBAppMathParser ON CACHE BOOL "")
set(Module_OTBAppProjection ON CACHE BOOL "")
set(Module_OTBSAR ON CACHE BOOL "")
set(Module_OTBVectorDataProcessing ON CACHE BOOL "")
set(Module_OTBPointSet ON CACHE BOOL "")
set(Module_OTBImageClassification ON CACHE BOOL "")
set(Module_OTBImageRegistration ON CACHE BOOL "")
